export interface customerTypeData {
        id:string,
        name:string,
        tob:string,
        bid:string,
        tinb:string,
        bbc:string,
        bpc:string
}

interface customerInput{
    actName:string,
    name:string
}

export let invoceData = [
    {
        id:"3fa85f64-5717-4562-b3fc-2c963f66afa6",
        header:{
            sbc: "",
            bid: "",
            bpc: "",
            bbc: "",
            bpn: "",
            ft: 0,
            scln: "",
            scc: "",
            crn: "",
            cdcn: "",
            cdcd: 0,
            billid: "",
            tprdis: 0,
            tdis: 0,
            tadis: 0,
            tvam: 0,
            todam: 0,
            tbill: 0,
            tonw: 0,
            torv: 0,
            tocv: 0,
            setm: 0,
            cap: 0,
            insp: 0,
            tvop: 0,
            taxid: "",
            indatim: "2023-08-11T09:26:37.677Z",
            inty: 0,
            inno: "25",
            irtaxid: "",
            inp: 0,
            ins: 0,
            tins: "",
            tinb: "10102520001",
            tob: 0,
            Tax17: 0,
            Indati2m: "2023-08-11T09:26:37.677Z"
        },
        body:[
            {
                sstid: "",
                sstt: "",
                mu: "",
                am: 0,
                nw: 0,
                fee: 0,
                cfee: 0,
                cut: "",
                exr: 0,
                ssrv: 0,
                sscv: 0,
                prdis: 0,
                dis: 0,
                adis: 0,
                vra: 0,
                vam: 0,
                odt: "",
                odr: 0,
                odam: 0,
                olt: "",
                olr: 0,
                olam: 0,
                consfee: 0,
                spro: 0,
                bros: 0,
                tcpbs: 0,
                cop: 0,
                vop: 0,
                bsrn: "",
                tsstam: 0
            }
        ],
        payments:{
            iinn: "",
            acn: "",
            trmn: "",
            pmt: 0,
            trn: "",
            pcn: "",
            pid: "",
            pdt: "2023-08-11T09:26:37.677Z",
            pv: 0
        },
        extension:{},
        response:{
            status:"pending",
            taxId:"A11W2T15000521000202",
        },
    },
    {
        id:"3fa85f64-5717-4562-b3fc-2c963f66afa6",
        header:{
            sbc: "",
            bid: "",
            bpc: "",
            bbc: "",
            bpn: "",
            ft: 0,
            scln: "",
            scc: "",
            crn: "",
            cdcn: "",
            cdcd: 0,
            billid: "",
            tprdis: 0,
            tdis: 0,
            tadis: 0,
            tvam: 0,
            todam: 0,
            tbill: 0,
            tonw: 0,
            torv: 0,
            tocv: 0,
            setm: 0,
            cap: 0,
            insp: 0,
            tvop: 0,
            taxid: "",
            indatim: "2023-08-11T09:26:37.677Z",
            inty: 0,
            inno: "57362",
            irtaxid: "",
            inp: 0,
            ins: 0,
            tins: "",
            tinb: "10102808625",
            tob: 0,
            Tax17: 0,
            Indati2m: "2023-08-11T09:26:37.677Z"
        },
        body:[
            {
                sstid: "",
                sstt: "",
                mu: "",
                am: 0,
                nw: 0,
                fee: 0,
                cfee: 0,
                cut: "",
                exr: 0,
                ssrv: 0,
                sscv: 0,
                prdis: 0,
                dis: 0,
                adis: 0,
                vra: 0,
                vam: 0,
                odt: "",
                odr: 0,
                odam: 0,
                olt: "",
                olr: 0,
                olam: 0,
                consfee: 0,
                spro: 0,
                bros: 0,
                tcpbs: 0,
                cop: 0,
                vop: 0,
                bsrn: "",
                tsstam: 0
            }
        ],
        payments:{
            iinn: "",
            acn: "",
            trmn: "",
            pmt: 0,
            trn: "",
            pcn: "",
            pid: "",
            pdt: "2023-08-11T09:26:37.677Z",
            pv: 0
        },
        extension:{},
        response:{
            status:"success",
            taxId:"A11W2T15000521000001",
        },
    },
    {
        id:"3fa85f64-5717-4562-b3fc-2c963f66afa6",
        header:{
            sbc: "",
            bid: "",
            bpc: "",
            bbc: "",
            bpn: "",
            ft: 0,
            scln: "",
            scc: "",
            crn: "",
            cdcn: "",
            cdcd: 0,
            billid: "",
            tprdis: 0,
            tdis: 0,
            tadis: 0,
            tvam: 0,
            todam: 0,
            tbill: 0,
            tonw: 0,
            torv: 0,
            tocv: 0,
            setm: 0,
            cap: 0,
            insp: 0,
            tvop: 0,
            taxid: "",
            indatim: "2023-08-11T09:26:37.677Z",
            inty: 0,
            inno: "57325",
            irtaxid: "",
            inp: 0,
            ins: 0,
            tins: "",
            tinb: "10102808245",
            tob: 0,
            Tax17: 0,
            Indati2m: "2023-08-11T09:26:37.677Z"
        },
        body:[
            {
                sstid: "",
                sstt: "",
                mu: "",
                am: 0,
                nw: 0,
                fee: 0,
                cfee: 0,
                cut: "",
                exr: 0,
                ssrv: 0,
                sscv: 0,
                prdis: 0,
                dis: 0,
                adis: 0,
                vra: 0,
                vam: 0,
                odt: "",
                odr: 0,
                odam: 0,
                olt: "",
                olr: 0,
                olam: 0,
                consfee: 0,
                spro: 0,
                bros: 0,
                tcpbs: 0,
                cop: 0,
                vop: 0,
                bsrn: "",
                tsstam: 0
            }
        ],
        payments:{
            iinn: "",
            acn: "",
            trmn: "",
            pmt: 0,
            trn: "",
            pcn: "",
            pid: "",
            pdt: "2023-08-11T09:26:37.677Z",
            pv: 0
        },
        extension:{},
        response:{
            status:"pending",
            taxId:"A11W2T150005210002c6",
        },
    },
    {
        id:"3fa85f64-5717-4562-b3fc-2c963f66afa6",
        header:{
            sbc: "",
            bid: "",
            bpc: "",
            bbc: "",
            bpn: "",
            ft: 0,
            scln: "",
            scc: "",
            crn: "",
            cdcn: "",
            cdcd: 0,
            billid: "",
            tprdis: 0,
            tdis: 0,
            tadis: 0,
            tvam: 0,
            todam: 0,
            tbill: 0,
            tonw: 0,
            torv: 0,
            tocv: 0,
            setm: 0,
            cap: 0,
            insp: 0,
            tvop: 0,
            taxid: "",
            indatim: "2023-08-11T09:26:37.677Z",
            inty: 0,
            inno: "25",
            irtaxid: "",
            inp: 0,
            ins: 0,
            tins: "",
            tinb: "10102520001",
            tob: 0,
            Tax17: 0,
            Indati2m: "2023-08-11T09:26:37.677Z"
        },
        body:[
            {
                sstid: "",
                sstt: "",
                mu: "",
                am: 0,
                nw: 0,
                fee: 0,
                cfee: 0,
                cut: "",
                exr: 0,
                ssrv: 0,
                sscv: 0,
                prdis: 0,
                dis: 0,
                adis: 0,
                vra: 0,
                vam: 0,
                odt: "",
                odr: 0,
                odam: 0,
                olt: "",
                olr: 0,
                olam: 0,
                consfee: 0,
                spro: 0,
                bros: 0,
                tcpbs: 0,
                cop: 0,
                vop: 0,
                bsrn: "",
                tsstam: 0
            }
        ],
        payments:{
            iinn: "",
            acn: "",
            trmn: "",
            pmt: 0,
            trn: "",
            pcn: "",
            pid: "",
            pdt: "2023-08-11T09:26:37.677Z",
            pv: 0
        },
        extension:{},
        response:{
            status:"pending",
            taxId:"A11W2T15000521000202",
        },
    },
    {
        id:"3fa85f64-5717-4562-b3fc-2c963f66afa6",
        header:{
            sbc: "",
            bid: "",
            bpc: "",
            bbc: "",
            bpn: "",
            ft: 0,
            scln: "",
            scc: "",
            crn: "",
            cdcn: "",
            cdcd: 0,
            billid: "",
            tprdis: 0,
            tdis: 0,
            tadis: 0,
            tvam: 0,
            todam: 0,
            tbill: 0,
            tonw: 0,
            torv: 0,
            tocv: 0,
            setm: 0,
            cap: 0,
            insp: 0,
            tvop: 0,
            taxid: "",
            indatim: "2023-08-11T09:26:37.677Z",
            inty: 0,
            inno: "25",
            irtaxid: "",
            inp: 0,
            ins: 0,
            tins: "",
            tinb: "10102520001",
            tob: 0,
            Tax17: 0,
            Indati2m: "2023-08-11T09:26:37.677Z"
        },
        body:[
            {
                sstid: "",
                sstt: "",
                mu: "",
                am: 0,
                nw: 0,
                fee: 0,
                cfee: 0,
                cut: "",
                exr: 0,
                ssrv: 0,
                sscv: 0,
                prdis: 0,
                dis: 0,
                adis: 0,
                vra: 0,
                vam: 0,
                odt: "",
                odr: 0,
                odam: 0,
                olt: "",
                olr: 0,
                olam: 0,
                consfee: 0,
                spro: 0,
                bros: 0,
                tcpbs: 0,
                cop: 0,
                vop: 0,
                bsrn: "",
                tsstam: 0
            }
        ],
        payments:{
            iinn: "",
            acn: "",
            trmn: "",
            pmt: 0,
            trn: "",
            pcn: "",
            pid: "",
            pdt: "2023-08-11T09:26:37.677Z",
            pv: 0
        },
        extension:{},
        response:{
            status:"failed",
            taxId:"A11W2T1500052101c253",
        },
    },
    {
        id:"3fa85f64-5717-4562-b3fc-2c963f66afa6",
        header:{
            sbc: "",
            bid: "",
            bpc: "",
            bbc: "",
            bpn: "",
            ft: 0,
            scln: "",
            scc: "",
            crn: "",
            cdcn: "",
            cdcd: 0,
            billid: "",
            tprdis: 0,
            tdis: 0,
            tadis: 0,
            tvam: 0,
            todam: 0,
            tbill: 0,
            tonw: 0,
            torv: 0,
            tocv: 0,
            setm: 0,
            cap: 0,
            insp: 0,
            tvop: 0,
            taxid: "",
            indatim: "2023-08-11T09:26:37.677Z",
            inty: 0,
            inno: "25",
            irtaxid: "",
            inp: 0,
            ins: 0,
            tins: "",
            tinb: "10102520001",
            tob: 0,
            Tax17: 0,
            Indati2m: "2023-08-11T09:26:37.677Z"
        },
        body:[
            {
                sstid: "",
                sstt: "",
                mu: "",
                am: 0,
                nw: 0,
                fee: 0,
                cfee: 0,
                cut: "",
                exr: 0,
                ssrv: 0,
                sscv: 0,
                prdis: 0,
                dis: 0,
                adis: 0,
                vra: 0,
                vam: 0,
                odt: "",
                odr: 0,
                odam: 0,
                olt: "",
                olr: 0,
                olam: 0,
                consfee: 0,
                spro: 0,
                bros: 0,
                tcpbs: 0,
                cop: 0,
                vop: 0,
                bsrn: "",
                tsstam: 0
            }
        ],
        payments:{
            iinn: "",
            acn: "",
            trmn: "",
            pmt: 0,
            trn: "",
            pcn: "",
            pid: "",
            pdt: "2023-08-11T09:26:37.677Z",
            pv: 0
        },
        extension:{},
        response:{
            status:"failed",
            taxId:"A11W2T1500052101c253",
        },
    },
    {
        id:"3fa85f64-5717-4562-b3fc-2c963f66afa6",
        header:{
            sbc: "",
            bid: "",
            bpc: "",
            bbc: "",
            bpn: "",
            ft: 0,
            scln: "",
            scc: "",
            crn: "",
            cdcn: "",
            cdcd: 0,
            billid: "",
            tprdis: 0,
            tdis: 0,
            tadis: 0,
            tvam: 0,
            todam: 0,
            tbill: 0,
            tonw: 0,
            torv: 0,
            tocv: 0,
            setm: 0,
            cap: 0,
            insp: 0,
            tvop: 0,
            taxid: "",
            indatim: "2023-08-11T09:26:37.677Z",
            inty: 0,
            inno: "1",
            irtaxid: "",
            inp: 0,
            ins: 0,
            tins: "",
            tinb: "12731027620001",
            tob: 0,
            Tax17: 0,
            Indati2m: "2023-08-11T09:26:37.677Z"
        },
        body:[
            {
                sstid: "",
                sstt: "",
                mu: "",
                am: 0,
                nw: 0,
                fee: 0,
                cfee: 0,
                cut: "",
                exr: 0,
                ssrv: 0,
                sscv: 0,
                prdis: 0,
                dis: 0,
                adis: 0,
                vra: 0,
                vam: 0,
                odt: "",
                odr: 0,
                odam: 0,
                olt: "",
                olr: 0,
                olam: 0,
                consfee: 0,
                spro: 0,
                bros: 0,
                tcpbs: 0,
                cop: 0,
                vop: 0,
                bsrn: "",
                tsstam: 0
            }
        ],
        payments:{
            iinn: "",
            acn: "",
            trmn: "",
            pmt: 0,
            trn: "",
            pcn: "",
            pid: "",
            pdt: "2023-08-11T09:26:37.677Z",
            pv: 0
        },
        extension:{},
        response:{
            status:"success",
            taxId:"A11W2T1500052100001",
        },
    },
    {
        id:"3fa85f64-5717-4562-b3fc-2c963f66afa6",
        header:{
            sbc: "",
            bid: "",
            bpc: "",
            bbc: "",
            bpn: "",
            ft: 0,
            scln: "",
            scc: "",
            crn: "",
            cdcn: "",
            cdcd: 0,
            billid: "",
            tprdis: 0,
            tdis: 0,
            tadis: 0,
            tvam: 0,
            todam: 0,
            tbill: 0,
            tonw: 0,
            torv: 0,
            tocv: 0,
            setm: 0,
            cap: 0,
            insp: 0,
            tvop: 0,
            taxid: "",
            indatim: "2023-08-11T09:26:37.677Z",
            inty: 0,
            inno: "25",
            irtaxid: "",
            inp: 0,
            ins: 0,
            tins: "",
            tinb: "10102520001",
            tob: 0,
            Tax17: 0,
            Indati2m: "2023-08-11T09:26:37.677Z"
        },
        body:[
            {
                sstid: "",
                sstt: "",
                mu: "",
                am: 0,
                nw: 0,
                fee: 0,
                cfee: 0,
                cut: "",
                exr: 0,
                ssrv: 0,
                sscv: 0,
                prdis: 0,
                dis: 0,
                adis: 0,
                vra: 0,
                vam: 0,
                odt: "",
                odr: 0,
                odam: 0,
                olt: "",
                olr: 0,
                olam: 0,
                consfee: 0,
                spro: 0,
                bros: 0,
                tcpbs: 0,
                cop: 0,
                vop: 0,
                bsrn: "",
                tsstam: 0
            }
        ],
        payments:{
            iinn: "",
            acn: "",
            trmn: "",
            pmt: 0,
            trn: "",
            pcn: "",
            pid: "",
            pdt: "2023-08-11T09:26:37.677Z",
            pv: 0
        },
        extension:{},
        response:{
            status:"failed",
            taxId:"A11W2T1500052101c253",
        },
    },
]

export let customerData:customerTypeData[] = [
    {
        id:'5632-89651C125-1245',
        name:'علی محمد حسینی',
        tob:'1',
        bid:'1273102762',
        tinb:'12731027620001',
        bbc:'1',
        bpc:'9536211965'
    },
    {
        id:'5632-89651F124-1135',
        name:'فریمهر راضی',
        tob:'1',
        bid:'0055316230',
        tinb:'00553162300002',
        bbc:'1',
        bpc:'1289621212'
    },
    {
        id:'5632-89651F124-1135',
        name:'خدمات ارتباطی ایرانسل',
        tob:'2',
        bid:'14001212325',
        tinb:'14001212325',
        bbc:'',
        bpc:''
    },
    {
        id:'5632-89651F124-1135',
        name:'کارگزاری آگاه',
        tob:'2',
        bid:'10102761459',
        tinb:'10102761459',
        bbc:'',
        bpc:''
    },
]

export const customerInput:customerInput[] = [
    {actName:'bid',name:'شناسه ملی خریدار'},
    {actName:'name',name:'نام خرید'},
    {actName:'tinb',name:'شناسه اقتصادی خریدار'},
    {actName:'tob',name:'نوع خریدار'},
    {actName:'bbc',name:'کد شعبه'},
    {actName:'bpc',name:'کدپستی'},
]